---
 - name: install nopcommerce
   become : yes
   hosts: all
   tasks:
    - name: install dpkg packages
      get_url:  
        url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb 
        dest: /home/ubuntu
      notify: 
        - install the debian package
   handlers:
     - name: install debian package
       ansible.builtin.dpkg_selections:
         name: install debian packages
         selections: install
    # - name: install package
    #   apt:
    #     deb: /tmp/packages-microsoft-prod.deb
     - name: clean package
       ansible.builtin.file:
         path: /home/ubuntu
         state: absent
     - name: http action 
       ansible.builtin.apt:
         name: apt-transport-https
         state: present
         update_cache: yes
         become: true
     - name: Install .NET Core SDK
       ansible.builtin.apt:
         name: dotnet-sdk-7.0
         state: present
         update_cache: yes
         become: true
     - name: create directory
       ansible.builtin.file:
         src: /nop
         state: directory
     - name: change directory
       command: cd /nop
       become: yes
     - name: install wget 
       ansible.builtin.get_url:
         url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.5/nopCommerce_4.60.5_NoSource_linux_x64.zip
         dest: /nop/nopCommerce_4.60.5_NoSource_linux_x64.zip
     - name: unzip
       ansible.builtin.unarchive:
         src: /nop/nopCommerce_4.60.5_NoSource_linux_x64.zip
         dest: /nop
         remote_src: yes
     - name: create directory
       ansible.builtin.file:
         src: /nop/bin        
         state: directory 
     - name: create directory
       ansible.builtin.file:
         src: /nop/logs
         state: directory
     - name: run command nop.web.dll
       command: /usr/bin/dotnet Nop.Web.dll --urls "http://0.0.0.0:5000"
       host: 0.0.0.0 
       port: 5000
     - name: create service file 
       ansible.builtin.file:
         path: /etc/systemd/system/nopCommerce.service
         state: touch
     - name: copy service file
       ansible.builtin.template:
         src: nopcommerce.service.j2
         dest: /etc/systemd/system/nopCommerce.service
     - name: service file excution
       ansible.builtin.service:
         name: service 
         state: started
         enabled: yes 


