---
 - name: activity2
   become: yes
   hosts: all
   tasks:
     - name: php installation on apache2
       ansible.builtin.apt:
         name: 
           - apache2
           - php 
           - libapache2-mod-php 
           - php-mysql
         state: present
         update_cache: yes
     - name: copy php file
       ansible.builtin.copy:
         content: '<?php phpinfo(); ?>'
         dest: /var/www/html/info.php
         remote_src: yes

